import pankake1 from "../Images/pankake1.jpg";
import donut1 from "../Images/donuts1.jpg";
import mysli1 from "../Images/mysli1.jpg";
import noodles1 from "../Images/noodles1.jpg";
import pasta1 from "../Images/pasta1.jpg";
import pie1 from "../Images/pie1.jpg";
let rese = [
    {
        name: "Blueberry Pancakes",
        image: pankake1,
        FoodType: "desert",
        ingredients: [
            "3/4 cup milk",
            "2 tablespoons white vinegar",
            "1 cup flour",
            "2 tablespoons sugar",
            "1 teaspoon baking powder",
            "1/2 teaspoon baking soda",
            "1/2 teaspoon salt",
            "1 egg",
            "2 tablespoons melted butter",
            "1+ cup fresh blueberries",
            "more butter for the pan",
        ],
        steps: [
            "Mix the milk and vinegar and let it sit for a minute or two (you’re making “buttermilk” here).",
            "Whisk the dry ingredients together. Whisk the egg, milk, and melted butter into the dry ingredients until just combined.",
            "Heat a nonstick pan over medium heat. Melt a little smear of butter in the pan (essential for giving a yummy golden brown crust).",
            "Pour about 1/3 cup of batter into the hot skillet and spread it flat-like (it will be pretty thick). Arrange a few blueberries on top. Cook until you see little bubbles on top and the edges starting to firm up. Flip and cook for another 1-2 minutes until the pancakes are sky-high fluffy and cooked through.",
            "Serve with butter and maple syrup. But honestly, sometimes I just like to eat these plain. YUM, YUM, YUM.",
        ],
    },
    {
        name: "Chocolate Donuts",
        image: donut1,
        FoodType: "desert",
        ingredients: [
            "1 cup (140g) all-purpose flour",
            "1/4 cup (25g) unsweetened cocoa powder",
            "1/2 teaspoon baking powder",
            "1/2 teaspoon baking soda",
            "1/8 teaspoon salt",
            "1 large egg",
            "1/2 cup (100g) granulated sugar",
            "1/3 cup (80 ml) milk",
            "1/4 cup (60 ml) yogurt",
            "2 tablespoons (30g) unsalted butter, melted",
            "1/2 teaspoon vanilla extract",
        ],
        steps: [
            "Preheat oven to 350°F/180°. Grease a donut pan with oil or butter. Set aside.",
            "Make the donuts: Whisk together the flour, cocoa powder, baking powder, baking soda, and salt in a large bowl. Set aside.",
            "In a medium bowl whisk egg with sugar until well combined. Add milk, yogurt, melted butter and vanilla extract, and whisk until combined. Pour into the flour mixture and mix until just combined. The batter will be thick.",
            "Fill donut cavities with batter ¾ way full using a spoon or a piping bag (much easier). Cut a corner off the bottom of the bag and pipe the batter into each donut cup.",
            "Bake for 9–10 minutes or until a toothpick inserted into the center of the donuts comes out clean. Allow to cool for 5 minutes in pan, then remove donuts from pan and transfer to a wire rack. Allow to cool completely before glazing.",
            "Make the chocolate glaze: Melt the chocolate, heavy cream, and butter gently in the microwave (in 30-second intervals, stirring in between) or a double boiler until smooth. Dip the tops of the donuts into the chocolate glaze, and place on a cooling rack to set.",
            "Donuts are best eaten the same day or keep them for up to 3 days in the refrigerator.",
        ],
    },
    {
        name: "Simple Mysli",
        image: mysli1,
        FoodType: "Morning",
        ingredients: [
            "3 1/2 cups rolled oats",
            "1/2 cup wheat bran",
            "1/2 teaspoon kosher salt",
            "1/2 teaspoon ground cinnamon",
            "1/2 cup sliced almonds",
            "1/4 cup raw pecans, coarsely chopped",
            "1/4 cup raw pepitas (shelled pumpkin seeds)",
            "1/2 cup unsweetened coconut flakes",
            "1/4 cup dried apricots, coarsely chopped",
            "1/4 cup dried cherries",
        ],
        steps: [
            "Toast the grains, nuts, and seeds. Arrange 2 racks to divide the oven into thirds and heat to 350°F. Place the oats, wheat bran, salt, and cinnamon on a rimmed baking sheet; toss to combine; and spread into an even layer. Place the almonds, pecans, and pepitas on a second rimmed baking sheet; toss to combine; and spread into an even layer. Transfer both baking sheets to oven, placing oats on top rack and nuts on bottom. Bake until nuts are fragrant, 10 to 12 minutes.",
            "Add the coconut. Remove the baking sheet with the nuts and set aside to cool. Sprinkle the coconut over the oats, return to the upper rack, and bake until the coconut is golden-brown, about 5 minutes more. Remove from oven and set aside to cool, about 10 minutes.",
            "Transfer to a large bowl. Transfer the contents of both baking sheets to a large bowl.",
            "Add the dried fruit. Add the apricots and cherries and toss to combine.",
            "Transfer to an airtight container. Muesli can be stored in an airtight container at room temperature for up to 1 month.",
            "Enjoy as desired. Enjoy as oatmeal, cereal, overnight oats, or with yogurt, topped with fresh fruit and a drizzle of honey or maple syrup, if desired.",
        ],
    },
    {
        name: "Noodle Soup",
        image: noodles1,
        FoodType: "lunch",
        ingredients: [
            "4 cups chicken stock",
            "3 green onions finely sliced into rounds",
            "1 tablespoon Oyster Sauce",
            "1 tablespoon low sodium Soy Sauce",
            "1 tablespoon low sodium dark Soy Sauce (this can be held until the end and added if needed by taste).",
            "4 oz Dried Chinese noodles of your choice",
            "4 leaves Bok Choy/pak choi sliced",
        ],
        steps: [
            "In a large saucepan, heat the chicken stock and bring to a boil.",
            "A pot of boiling chicken stock",
            "Add the green onions.",
            "the green onions added to the stock in the pot",
            "Add the Bok Choy or Chinese greens.",
            "the green onions and Chinese greens added to the stock in the pot",
            "Add light & Dark soy sauce.",
            "The soup with the soy sauces and oyster sauce added to the stock in the pan",
            "Add the oyster sauce.",
            "The soup with the oyster sauce added to the stock in the pan",
            "Add the noodles right into the soup.",
            "three nests of Chinese noodles added to the pot with the soup",
            "Follow the instructions on your noodle’s package for the cooking time. ",
            "The cooked soup in the pot ready to serve",
            "Once cooked, serve and enjoy!",
        ],
    },
    {
        name: "Chicken Pasta",
        image: pasta1,
        FoodType: "lunch",
        ingredients: [
            "10 ounces dry pasta (any kind)",
            "1 pound boneless skinless chicken breast",
            "1 teaspoon ",
            "1 teaspoon Italian seasoning",
            "1 teaspoon ",
            "salt & pepper to taste",
            "2 tablespoons olive oil",
            "1 tablespoon butter",
            "4 cloves garlic minced",
            "1 cup tomatoes diced",
            "2 cups spinach chopped, optional",
            "2 cups heavy cream (or 16 oz)",
            "1/2 cups Parmesan cheese shredded or grated",
            "salt & pepper to taste",
        ],
        steps: [
            "Prep Pasta: Boil water in a large pot and cook pasta al dente according to package instructions.",
            "Season both sides of chicken breasts with salt garlic powder, Italian seasoning, paprika, and a generous pinch of salt and pepper.",
            "Heat olive oil in a large heavy duty pan over medium-high heat and cook chicken breasts 5 minutes per side or until cooked through. Remove from heat and set aside.",
            "To the same pan, add the butter and garlic and cook for 1 minute or until fragrant. Add the tomato and spinach and cook 2-3 minutes or until the tomato and spinach are soft and wilted.",
            "Reduce the heat and add the heavy cream and parmesan cheese. Whisk until fully incorporated and creamy. Add a pinch of salt and pepper to taste.",
            "Drain pasta and slice chicken into thin slices or cubes and return to the same pan. Stir to combine and serve!",
        ],
    },
    {
        name: "Moms Pie",
        image: pie1,
        FoodType: "lunch",
        ingredients: [
            "1 tbsp olive oil",
            "1 large onion, finely chopped",
            "3 thyme sprigs, leaves picked",
            "2 garlic cloves, crushed",
            "350g chicken breasts, cut into small chunks",
            "250g chestnut mushrooms, sliced",
            "300ml chicken stock",
            "100g crème fraîche",
            "1 tbsp wholegrain mustard",
            "100g kale",
            "2 tsp cornflour, mixed with 1 tbsp cold water",
            "375g pack puff pastry, rolled into a circle slightly bigger than your dish",
            "1 egg yolk, to glaze",
        ],
        steps: [
            "Heat ½ tbsp oil over a gentle heat in a flameproof casserole dish. Add the onion and cook for 5 mins until softening. Scatter over the thyme and garlic, and stir for 1 min. Turn up the heat and add the chicken, frying until golden but not fully cooked. Add the mushrooms and the remaining oil. Heat oven to 200C/180 fan/gas 6.",
            "Add the stock, crème fraîche, mustard and kale, and season well. Add the cornflour mixture and stir until thickened a little.",
            "Remove from the heat and cover with the puff pastry lid, pressing into the sides of the casserole dish. Slice a cross in the centre and glaze with the egg. Bake for 30 mins until the pastry is puffed up and golden.",
        ],
    },
];
export { rese };
